package com.booking.booking.utils;

public enum EventCategory {
    MUSIC, ART, THEATER, DANCE, COMEDY,
    EDUCATION, WORKSHOP, CONFERENCE, NETWORKING, TECHNOLOGY,
    GAMING, SPORTS, FITNESS, WELLNESS, HEALTH,
    FOOD, TRAVEL, CHARITY, FASHION, CULTURE,
    STARTUP, BUSINESS, RELIGION, COMMUNITY
}