spring:
    application:
        name: booking
    datasource:
        url: jdbc:postgresql://localhost:5432/bookingEvent
        username: mmaqbour
        password: mmaqbour
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true

security:
    jwt:
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        expiration-time: 3600000

application:
    file:
        uploads:
            photos-output-path: ./uploads
    stripe:
        api_key: k_test_51QyX2k2f0IUkWUsZ8aK7XcW8gs5KkGck4zsuW3JIhmJSepukiurKONjcSRkKA53JJ6WpBoHMwEZhgVatLa7czILO00gKc6SeKf

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true